- name: variables
  hosts: localhost
  vars:  # variable declaration
    course: "terraform"
    from: "Learn devops"
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "hi, we are learning {{ course }} from {{ from }}"