- name: variables
  hosts: localhost
  # vars:
  #   course: "terraform"
  #   from: "Learn devops"
  tasks:
    - name: print information
      vars:
        course: "terraform"
      ansible.builtin.debug:
        msg: "hi, we are learning {{ course }}"