 - name: variables
   hosts: localhost
   vars: #varible declaration
     Course: "terraform"
     from: "Learn devops"
   tasks:
   - name: print information
     ansible.builtin.debug:
      msg: "hi, we are learning {{course}} from {{from}}"