- name: variables
  hosts: localhost
  gather_facts: false

  vars:
    course: "terraform"
    from: "Learn devops"

  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "hi, we are learning {{ course }} from {{ from }}"