- name: variables
  hosts: localhost
  # vars:
  #   course: "terraform"
  #   from: "Learn devops"
  vars_files:
  - vars-files.yaml
  tasks:
    - name: print information
      # vars:
      #   course: "terraform"
      ansible.builtin.debug:
        msg: "hi, i am {{name}} i am working as {{Designation}} in {{company}}"