- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter number
    private: not
  tasks:
    - name: number is less then 10
      ansible.builtin.debug:
        msg: "given number {{number}} is less then 10"
      when: number < 10
    - name: number is greater or equal to 10
      ansible.builtin.debug:
        msg: "given number {{number}} is greater or equal to 10"
      when: number >=  10