- name: conditions
  hosts: web
  tasks:
    - name: check user exists or not
      ansible.builtin.command: id expense
      register: USER
      ignore_errors: true

    - name: print user information
      ansible.builtin.debug:
        msg: "user info: {{USER}}"
    - name: creating user
      ansible.builtin.command: useradd expense
      when: USER.rc != 0  #CONDITION
      
    - name: say hello
      ansible.builtin.debug:
        msg: "hello"