- name: datatypes 
  hosts: localhost
  vars:
    course: devops with aws # string
    Tools:
    - linux
    - shell
    - ansible
    experience:
      devops: 3
      aws: 2
      Docker: 1
    realproject: true # boolean
  tasks:
    - name: print variables with datatypes
      ansible.builtin.debug:
        msg: "Course: {{course}}, tools covered {{Tools}}, experience is: {{experience}}, is realproject: {{realproject}}"